services:
  - type: worker
    name: telegram-video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python downloader_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
